name: Scruff Stuff
favicon: null
layout_spectrum: 0.14186075306497514
typography_spectrum: 0.7407250935211778
title: Scruff Stuff Beard Oil
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2e2334'
    - '#f2e9e2'
    - '#51414b'
    - '#745e60'
    - '#9c9497'
  brandStrength: 0.5
  lightness: 0.6374341826885939
  saturation: 0.8940154735464603
  rhythmicContrast: 0.9504962067585438
purpose: []
