name: Scruff Stuff
favicon: null
layout_spectrum: 0.25207
typography_spectrum: 0.74819
title: Scruff Stuff Beard Oil
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dedddb'
    - '#80766c'
    - '#191013'
    - '#3c3731'
    - '#f0d17f'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
